[package]
name = "hd44780-lcd"
version = "0.1.0"
authors = ["Jarrod Bennett"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.5"